### ISSUE TITLE
Create Order Details controller 

### ISSUE THREAD

**Issue by JamesSoaresCorreia** [comp231-S4G3/DineOut#28]

**Comment by edmarques14** [comment]
Do we still need this controller? I am asking because the view that I have created for the owner side seeing the order details was reallocated under Restaurant folder where RestauranController will have the action responsible for loading the orderDetails view.

**Comment by JamesSoaresCorreia** [comment]
As long as the action necessary to load it is taken care of or is being worked on, i think you're right and we don't need an entire controller dedicated to order details.
